dividend=int(input("dividend"))
divisor=int(input("divisor"))
quocient=(dividend)//(divisor)
residu=(dividend)%(divisor)
print(f"Divisió: {dividend}/{divisor}")
print(f"Quocient: {quocient}")
print(f"Residu: {residu}")